# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8HKH9PpUR1acfMfCwPf4zPCfvoWXeih
"""

import streamlit as st
from prediction_page import show_page

show_page()